#!/usr/bin/env php
<?php
/**
 * This file is used as command line controller. It grabs the Oldstyle Application object
 * and executes it.
 *
 * For integrating with "regular" PHP, you will want to grab the Application object in
 * the same way, and then using the result of that for manipulating
 *
 * @var Oldstyle $application
 */

use etiqa\Oldstyle\Oldstyle;

$application = include dirname(__FILE__) . '/application.php';
$application->run();